// AUTO-GENERATED by scripts/scaffold/extract-redirects.ts
// Do not edit manually. Re-run the script if data/webflow/ changes.
import type { Redirect } from 'next/dist/lib/load-custom-routes'

export const crawlRedirects: Redirect[] = [
  {
    "source": "/start-hiring/get-started",
    "destination": "/start-hiring/contact-info",
    "permanent": true
  },
  {
    "source": "/tools/price-comparison-calculator",
    "destination": "/pricing",
    "permanent": true
  },
  {
    "source": "/compare/cloud-employee-vs-arc-dev",
    "destination": "/compare",
    "permanent": true
  },
  {
    "source": "/download/weekly-self-reporting-system",
    "destination": "/downloads",
    "permanent": true
  },
  {
    "source": "/download/our-internal-hiring-sop",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/managing-engineers/software-developer-performance-metrics-for-ctos",
    "destination": "/managing-engineers",
    "permanent": true
  },
  {
    "source": "/videos/how-to-hire-top-developers-in-7-days",
    "destination": "/videos",
    "permanent": true
  },
  {
    "source": "/hiring-tips/how-to-hire-python-developers",
    "destination": "/hiring-tips",
    "permanent": true
  },
  {
    "source": "/scaling-teams/scaling-product-development-with-remote-software-developers",
    "destination": "/scaling-teams",
    "permanent": true
  },
  {
    "source": "/uk/customer-stories/salmon-software",
    "destination": "/uk/customer-story/salmon-software",
    "permanent": true
  },
  {
    "source": "/uk/customer-stories/event-connections",
    "destination": "/uk/customer-story/event-connections",
    "permanent": true
  },
  {
    "source": "/reviews/mercato",
    "destination": "/reviews",
    "permanent": true
  }
]
