// GENERATED by scripts/scaffold/generate-job-role-redirects.ts - do not hand-edit.
//
// One rule per job slug, taken from Webflow's redirect export, NOT a catch-all.
// Webflow does not redirect every /live-job-role/ URL that ever existed: 29 of them
// are absent from its list and it 404s them, and their talent-site destinations are
// 404s too. A catch-all sent those 29 into a cross-domain redirect chain ending in a
// dead page, which is worse than the clean 404 the live site serves.
//
// Regenerate: npm run redirects:job-roles
import type { Redirect } from 'next/dist/lib/load-custom-routes'

export const jobRoleRedirects: Redirect[] = [
  {
    "source": "/live-job-role/core-android-developer1",
    "destination": "https://talent.cloudemployee.io/live-job-role/core-android-developer1",
    "permanent": true
  },
  {
    "source": "/live-job-role/cms-backend-administrator",
    "destination": "https://talent.cloudemployee.io/live-job-role/cms-backend-administrator",
    "permanent": true
  },
  {
    "source": "/live-job-role/data-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/data-engineer",
    "permanent": true
  },
  {
    "source": "/live-job-role/ai-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/ai-engineer",
    "permanent": true
  },
  {
    "source": "/live-job-role/c-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/c-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/backend-developer-python-devops-terraform",
    "destination": "https://talent.cloudemployee.io/live-job-role/backend-developer-python-devops-terraform",
    "permanent": true
  },
  {
    "source": "/live-job-role/aws-devops-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/aws-devops-engineer",
    "permanent": true
  },
  {
    "source": "/live-job-role/consultant-e-commerce-and-technology",
    "destination": "https://talent.cloudemployee.io/live-job-role/consultant-e-commerce-and-technology",
    "permanent": true
  },
  {
    "source": "/live-job-role/backend-software-engineer-php",
    "destination": "https://talent.cloudemployee.io/live-job-role/backend-software-engineer-php",
    "permanent": true
  },
  {
    "source": "/live-job-role/business-development-representative-bdr",
    "destination": "https://talent.cloudemployee.io/live-job-role/business-development-representative-bdr",
    "permanent": true
  },
  {
    "source": "/live-job-role/fullstack-net-developer11",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-net-developer11",
    "permanent": true
  },
  {
    "source": "/live-job-role/full-stack-senior-engineer001",
    "destination": "https://talent.cloudemployee.io/live-job-role/full-stack-senior-engineer001",
    "permanent": true
  },
  {
    "source": "/live-job-role/devops-cloud-infrastructure-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/devops-cloud-infrastructure-engineer",
    "permanent": true
  },
  {
    "source": "/live-job-role/full-stack-net-developer12",
    "destination": "https://talent.cloudemployee.io/live-job-role/full-stack-net-developer12",
    "permanent": true
  },
  {
    "source": "/live-job-role/junior-data-engineer-mid-level-python-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/junior-data-engineer-mid-level-python-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/project-manager-2",
    "destination": "https://talent.cloudemployee.io/live-job-role/project-manager-2",
    "permanent": true
  },
  {
    "source": "/live-job-role/core-ios-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/core-ios-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-net-developer-with-blazor",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-net-developer-with-blazor",
    "permanent": true
  },
  {
    "source": "/live-job-role/digital-commerce-associate-architect",
    "destination": "https://talent.cloudemployee.io/live-job-role/digital-commerce-associate-architect",
    "permanent": true
  },
  {
    "source": "/live-job-role/fullstack-vue-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-vue-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/sql-server-database-administrator-dba",
    "destination": "https://talent.cloudemployee.io/live-job-role/sql-server-database-administrator-dba",
    "permanent": true
  },
  {
    "source": "/live-job-role/qa-automation-engineer-fobdm",
    "destination": "https://talent.cloudemployee.io/live-job-role/qa-automation-engineer-fobdm",
    "permanent": true
  },
  {
    "source": "/live-job-role/enterprise-architect",
    "destination": "https://talent.cloudemployee.io/live-job-role/enterprise-architect",
    "permanent": true
  },
  {
    "source": "/live-job-role/growth-ae",
    "destination": "https://talent.cloudemployee.io/live-job-role/growth-ae",
    "permanent": true
  },
  {
    "source": "/live-job-role/mobile-and-web-developer-react-and-react-native",
    "destination": "https://talent.cloudemployee.io/live-job-role/mobile-and-web-developer-react-and-react-native",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-data-engineer-200",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-data-engineer-200",
    "permanent": true
  },
  {
    "source": "/live-job-role/part-time-manual-qa-tester-ph",
    "destination": "https://talent.cloudemployee.io/live-job-role/part-time-manual-qa-tester-ph",
    "permanent": true
  },
  {
    "source": "/live-job-role/data-analyst",
    "destination": "https://talent.cloudemployee.io/live-job-role/data-analyst",
    "permanent": true
  },
  {
    "source": "/live-job-role/data-scientist-01",
    "destination": "https://talent.cloudemployee.io/live-job-role/data-scientist-01",
    "permanent": true
  },
  {
    "source": "/live-job-role/qa-engineer---manual-automation-technical-documentation",
    "destination": "https://talent.cloudemployee.io/live-job-role/qa-engineer---manual-automation-technical-documentation",
    "permanent": true
  },
  {
    "source": "/live-job-role/scrum-master-thdgt",
    "destination": "https://talent.cloudemployee.io/live-job-role/scrum-master-thdgt",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-data-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-data-engineer",
    "permanent": true
  },
  {
    "source": "/live-job-role/fullstack-developer222",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-developer222",
    "permanent": true
  },
  {
    "source": "/live-job-role/qa-engineer1",
    "destination": "https://talent.cloudemployee.io/live-job-role/qa-engineer1",
    "permanent": true
  },
  {
    "source": "/live-job-role/frontend-software-engineer000",
    "destination": "https://talent.cloudemployee.io/live-job-role/frontend-software-engineer000",
    "permanent": true
  },
  {
    "source": "/live-job-role/machine-learning-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/machine-learning-engineer",
    "permanent": true
  },
  {
    "source": "/live-job-role/lead-full-stack-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/lead-full-stack-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/mid-level-3d-artist",
    "destination": "https://talent.cloudemployee.io/live-job-role/mid-level-3d-artist",
    "permanent": true
  },
  {
    "source": "/live-job-role/front-end-developer-mid-senior",
    "destination": "https://talent.cloudemployee.io/live-job-role/front-end-developer-mid-senior",
    "permanent": true
  },
  {
    "source": "/live-job-role/pmo-analyst-manager",
    "destination": "https://talent.cloudemployee.io/live-job-role/pmo-analyst-manager",
    "permanent": true
  },
  {
    "source": "/live-job-role/full-stack-senior-engineer-2",
    "destination": "https://talent.cloudemployee.io/live-job-role/full-stack-senior-engineer-2",
    "permanent": true
  },
  {
    "source": "/live-job-role/scrum-master",
    "destination": "https://talent.cloudemployee.io/live-job-role/scrum-master",
    "permanent": true
  },
  {
    "source": "/live-job-role/fullstack-software-engineer2",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-software-engineer2",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-backend-engineer1",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-backend-engineer1",
    "permanent": true
  },
  {
    "source": "/live-job-role/hubspot-crm-specialist",
    "destination": "https://talent.cloudemployee.io/live-job-role/hubspot-crm-specialist",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-backend-api-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-backend-api-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-android-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-android-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/qa-engineer-2",
    "destination": "https://talent.cloudemployee.io/live-job-role/qa-engineer-2",
    "permanent": true
  },
  {
    "source": "/live-job-role/mid-senior-net-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/mid-senior-net-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/fullstack-developer-mid---sr",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-developer-mid---sr",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-azure-devops-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-azure-devops-engineer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-web-developer-react-wordpress",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-web-developer-react-wordpress",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-qa-tester-manual-and-automation",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-qa-tester-manual-and-automation",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-integration-backend-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-integration-backend-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-data-engineer-202",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-data-engineer-202",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-frontend-engineer-web3-next-js",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-frontend-engineer-web3-next-js",
    "permanent": true
  },
  {
    "source": "/live-job-role/seniorlead-backend-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/seniorlead-backend-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-frontend-developer-15",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-frontend-developer-15",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-drupal-developer011",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-drupal-developer011",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-flutter-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-flutter-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-full-stack-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-full-stack-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-fullstack-javascript-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-fullstack-javascript-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-ios-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-ios-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-python-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-python-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-qa-tester",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-qa-tester",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-technical-writer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-technical-writer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-ui-developer-with-umbraco",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-ui-developer-with-umbraco",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-fullstack-python-developer-with-react",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-fullstack-python-developer-with-react",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-full-stack-net-blazor-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-full-stack-net-blazor-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-qa-tester-q3qlf",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-qa-tester-q3qlf",
    "permanent": true
  },
  {
    "source": "/live-job-role/seniorlead-backend-developer-brazil",
    "destination": "https://talent.cloudemployee.io/live-job-role/seniorlead-backend-developer-brazil",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-software-developer-php-laravel",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-software-developer-php-laravel",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-fullstack-php-laravel-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-fullstack-php-laravel-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-laravel-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-laravel-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-qa-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-qa-engineer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-devops-engineer-3",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-devops-engineer-3",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-fullstack-engineer-ngx8q",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-fullstack-engineer-ngx8q",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-hr-business-partner",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-hr-business-partner",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-salesforce-developer01",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-salesforce-developer01",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-video-editor",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-video-editor",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-quality-assurance-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-quality-assurance-engineer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-integrations-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-integrations-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-devops-engineer-2",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-devops-engineer-2",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-salesface-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-salesface-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/sr-software-eng001",
    "destination": "https://talent.cloudemployee.io/live-job-role/sr-software-eng001",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-ios-developer-2-416sr",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-ios-developer-2-416sr",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-frontend-developer-14",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-frontend-developer-14",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-data-engineer-201",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-data-engineer-201",
    "permanent": true
  },
  {
    "source": "/live-job-role/python-developer-sr-level",
    "destination": "https://talent.cloudemployee.io/live-job-role/python-developer-sr-level",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-software-engineer-vb6",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-software-engineer-vb6",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-dotnet-developer-85260",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-dotnet-developer-85260",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-mid-fullstack-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-mid-fullstack-engineer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-nuxt-vue-js-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-nuxt-vue-js-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-dotnet-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-dotnet-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/senior-technical-developer-php-ad-tech",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-technical-developer-php-ad-tech",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/full-stack-senior-engineer001",
    "destination": "https://talent.cloudemployee.io/live-job-role/full-stack-senior-engineer001",
    "permanent": true
  },
  {
    "source": "/live-job-role/technical-cv-sourcing-specialist",
    "destination": "https://talent.cloudemployee.io/live-job-role/technical-cv-sourcing-specialist",
    "permanent": true
  },
  {
    "source": "/live-job-role/seniorteam-lead-full-stack-php-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/seniorteam-lead-full-stack-php-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/technical-lead",
    "destination": "https://talent.cloudemployee.io/live-job-role/technical-lead",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/c-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/c-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/digital-commerce-associate-architect",
    "destination": "https://talent.cloudemployee.io/live-job-role/digital-commerce-associate-architect",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/fullstack-software-engineer2",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-software-engineer2",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/fullstack-vue-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-vue-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/data-analyst",
    "destination": "https://talent.cloudemployee.io/live-job-role/data-analyst",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/consultant-e-commerce-and-technology",
    "destination": "https://talent.cloudemployee.io/live-job-role/consultant-e-commerce-and-technology",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/front-end-developer-mid-senior",
    "destination": "https://talent.cloudemployee.io/live-job-role/front-end-developer-mid-senior",
    "permanent": true
  },
  {
    "source": "/live-job-role/software-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/software-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/fullstack-net-developer11",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-net-developer11",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/full-stack-senior-engineer-2",
    "destination": "https://talent.cloudemployee.io/live-job-role/full-stack-senior-engineer-2",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/frontend-software-engineer000",
    "destination": "https://talent.cloudemployee.io/live-job-role/frontend-software-engineer000",
    "permanent": true
  },
  {
    "source": "/live-job-role/test-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/test-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/full-stack-net-developer12",
    "destination": "https://talent.cloudemployee.io/live-job-role/full-stack-net-developer12",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/fullstack-developer-mid---sr",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-developer-mid---sr",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/fullstack-developer222",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-developer222",
    "permanent": true
  },
  {
    "source": "/live-job-role/strategy-operations-manager",
    "destination": "https://talent.cloudemployee.io/live-job-role/strategy-operations-manager",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/cms-backend-administrator",
    "destination": "https://talent.cloudemployee.io/live-job-role/cms-backend-administrator",
    "permanent": true
  },
  {
    "source": "/live-job-role/solution-architect-e-commerce",
    "destination": "https://talent.cloudemployee.io/live-job-role/solution-architect-e-commerce",
    "permanent": true
  },
  {
    "source": "/live-job-role/software-qa-test-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/software-qa-test-engineer",
    "permanent": true
  },
  {
    "source": "/live-job-role/solutions-architect",
    "destination": "https://talent.cloudemployee.io/live-job-role/solutions-architect",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/data-scientist-01",
    "destination": "https://talent.cloudemployee.io/live-job-role/data-scientist-01",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/enterprise-architect",
    "destination": "https://talent.cloudemployee.io/live-job-role/enterprise-architect",
    "permanent": true
  },
  {
    "source": "/live-job-role/ios-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/ios-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/transformation-project-manager",
    "destination": "https://talent.cloudemployee.io/live-job-role/transformation-project-manager",
    "permanent": true
  },
  {
    "source": "/live-job-role/shopify-team-lead",
    "destination": "https://talent.cloudemployee.io/live-job-role/shopify-team-lead",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/core-ios-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/core-ios-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/core-android-developer1",
    "destination": "https://talent.cloudemployee.io/live-job-role/core-android-developer1",
    "permanent": true
  },
  {
    "source": "/live-job-role/technical-customer-success-specialist",
    "destination": "https://talent.cloudemployee.io/live-job-role/technical-customer-success-specialist",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/aws-devops-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/aws-devops-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/ai-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/ai-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/backend-software-engineer-php",
    "destination": "https://talent.cloudemployee.io/live-job-role/backend-software-engineer-php",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/backend-developer-python-devops-terraform",
    "destination": "https://talent.cloudemployee.io/live-job-role/backend-developer-python-devops-terraform",
    "permanent": true
  },
  {
    "source": "/live-job-role/ui-ux-designer",
    "destination": "https://talent.cloudemployee.io/live-job-role/ui-ux-designer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/business-development-representative-bdr",
    "destination": "https://talent.cloudemployee.io/live-job-role/business-development-representative-bdr",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/data-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/data-engineer",
    "permanent": true
  },
  {
    "source": "/live-job-role/ui-engineer-frontend-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/ui-engineer-frontend-developer",
    "permanent": true
  },
  {
    "source": "/live-job-role/talent-acquisition-specialist",
    "destination": "https://talent.cloudemployee.io/live-job-role/talent-acquisition-specialist",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/devops-cloud-infrastructure-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/devops-cloud-infrastructure-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-fullstack-php-laravel-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-fullstack-php-laravel-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-fullstack-javascript-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-fullstack-javascript-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/mid-level-3d-artist",
    "destination": "https://talent.cloudemployee.io/live-job-role/mid-level-3d-artist",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/project-manager-2",
    "destination": "https://talent.cloudemployee.io/live-job-role/project-manager-2",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-data-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-data-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-full-stack-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-full-stack-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-data-engineer-202",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-data-engineer-202",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-backend-api-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-backend-api-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-drupal-developer011",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-drupal-developer011",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-frontend-engineer-web3-next-js",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-frontend-engineer-web3-next-js",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-flutter-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-flutter-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/pmo-analyst-manager",
    "destination": "https://talent.cloudemployee.io/live-job-role/pmo-analyst-manager",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/part-time-manual-qa-tester-ph",
    "destination": "https://talent.cloudemployee.io/live-job-role/part-time-manual-qa-tester-ph",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/qa-engineer-2",
    "destination": "https://talent.cloudemployee.io/live-job-role/qa-engineer-2",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-net-developer-with-blazor",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-net-developer-with-blazor",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-devops-engineer-2",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-devops-engineer-2",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/mobile-and-web-developer-react-and-react-native",
    "destination": "https://talent.cloudemployee.io/live-job-role/mobile-and-web-developer-react-and-react-native",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-data-engineer-200",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-data-engineer-200",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-devops-engineer-3",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-devops-engineer-3",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-fullstack-engineer-ngx8q",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-fullstack-engineer-ngx8q",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-azure-devops-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-azure-devops-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/growth-ae",
    "destination": "https://talent.cloudemployee.io/live-job-role/growth-ae",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/machine-learning-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/machine-learning-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/qa-automation-engineer-fobdm",
    "destination": "https://talent.cloudemployee.io/live-job-role/qa-automation-engineer-fobdm",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-frontend-developer-15",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-frontend-developer-15",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-android-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-android-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/junior-data-engineer-mid-level-python-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/junior-data-engineer-mid-level-python-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-frontend-developer-14",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-frontend-developer-14",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/sql-server-database-administrator-dba",
    "destination": "https://talent.cloudemployee.io/live-job-role/sql-server-database-administrator-dba",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-full-stack-net-blazor-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-full-stack-net-blazor-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-backend-engineer1",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-backend-engineer1",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-data-engineer-201",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-data-engineer-201",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/scrum-master-thdgt",
    "destination": "https://talent.cloudemployee.io/live-job-role/scrum-master-thdgt",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/lead-full-stack-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/lead-full-stack-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/qa-engineer1",
    "destination": "https://talent.cloudemployee.io/live-job-role/qa-engineer1",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/hubspot-crm-specialist",
    "destination": "https://talent.cloudemployee.io/live-job-role/hubspot-crm-specialist",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/qa-engineer---manual-automation-technical-documentation",
    "destination": "https://talent.cloudemployee.io/live-job-role/qa-engineer---manual-automation-technical-documentation",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/mid-senior-net-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/mid-senior-net-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/scrum-master",
    "destination": "https://talent.cloudemployee.io/live-job-role/scrum-master",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/talent-acquisition-specialist",
    "destination": "https://talent.cloudemployee.io/live-job-role/talent-acquisition-specialist",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-technical-writer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-technical-writer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-technical-developer-php-ad-tech",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-technical-developer-php-ad-tech",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-salesface-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-salesface-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-ui-developer-with-umbraco",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-ui-developer-with-umbraco",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/sr-software-eng001",
    "destination": "https://talent.cloudemployee.io/live-job-role/sr-software-eng001",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-software-engineer-vb6",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-software-engineer-vb6",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/seniorlead-backend-developer-brazil",
    "destination": "https://talent.cloudemployee.io/live-job-role/seniorlead-backend-developer-brazil",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-qa-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-qa-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-ios-developer-2-416sr",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-ios-developer-2-416sr",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/solution-architect-e-commerce",
    "destination": "https://talent.cloudemployee.io/live-job-role/solution-architect-e-commerce",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-software-developer-php-laravel",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-software-developer-php-laravel",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/seniorlead-backend-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/seniorlead-backend-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-web-developer-react-wordpress",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-web-developer-react-wordpress",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/seniorteam-lead-full-stack-php-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/seniorteam-lead-full-stack-php-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-video-editor",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-video-editor",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/strategy-operations-manager",
    "destination": "https://talent.cloudemployee.io/live-job-role/strategy-operations-manager",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-mid-fullstack-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-mid-fullstack-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/technical-lead",
    "destination": "https://talent.cloudemployee.io/live-job-role/technical-lead",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/solutions-architect",
    "destination": "https://talent.cloudemployee.io/live-job-role/solutions-architect",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/software-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/software-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/technical-cv-sourcing-specialist",
    "destination": "https://talent.cloudemployee.io/live-job-role/technical-cv-sourcing-specialist",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-integrations-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-integrations-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-integration-backend-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-integration-backend-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-hr-business-partner",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-hr-business-partner",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/python-developer-sr-level",
    "destination": "https://talent.cloudemployee.io/live-job-role/python-developer-sr-level",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-qa-tester-q3qlf",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-qa-tester-q3qlf",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-dotnet-developer-85260",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-dotnet-developer-85260",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-ios-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-ios-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-fullstack-python-developer-with-react",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-fullstack-python-developer-with-react",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-dotnet-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-dotnet-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-salesforce-developer01",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-salesforce-developer01",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-qa-tester",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-qa-tester",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-qa-tester-manual-and-automation",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-qa-tester-manual-and-automation",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-quality-assurance-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-quality-assurance-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-python-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-python-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-laravel-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-laravel-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/technical-customer-success-specialist",
    "destination": "https://talent.cloudemployee.io/live-job-role/technical-customer-success-specialist",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/senior-nuxt-vue-js-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-nuxt-vue-js-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/software-qa-test-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/software-qa-test-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/shopify-team-lead",
    "destination": "https://talent.cloudemployee.io/live-job-role/shopify-team-lead",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/data-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/data-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/test-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/test-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/ui-engineer-frontend-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/ui-engineer-frontend-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/growth-ae",
    "destination": "https://talent.cloudemployee.io/live-job-role/growth-ae",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/full-stack-net-developer12",
    "destination": "https://talent.cloudemployee.io/live-job-role/full-stack-net-developer12",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/data-scientist-01",
    "destination": "https://talent.cloudemployee.io/live-job-role/data-scientist-01",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/fullstack-developer-mid---sr",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-developer-mid---sr",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/lead-full-stack-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/lead-full-stack-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/backend-developer-python-devops-terraform",
    "destination": "https://talent.cloudemployee.io/live-job-role/backend-developer-python-devops-terraform",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/devops-cloud-infrastructure-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/devops-cloud-infrastructure-engineer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/fullstack-developer222",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-developer222",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/enterprise-architect",
    "destination": "https://talent.cloudemployee.io/live-job-role/enterprise-architect",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/hubspot-crm-specialist",
    "destination": "https://talent.cloudemployee.io/live-job-role/hubspot-crm-specialist",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/mid-senior-net-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/mid-senior-net-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/frontend-software-engineer000",
    "destination": "https://talent.cloudemployee.io/live-job-role/frontend-software-engineer000",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/pmo-analyst-manager",
    "destination": "https://talent.cloudemployee.io/live-job-role/pmo-analyst-manager",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/project-manager-2",
    "destination": "https://talent.cloudemployee.io/live-job-role/project-manager-2",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/part-time-manual-qa-tester-ph",
    "destination": "https://talent.cloudemployee.io/live-job-role/part-time-manual-qa-tester-ph",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/cms-backend-administrator",
    "destination": "https://talent.cloudemployee.io/live-job-role/cms-backend-administrator",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/digital-commerce-associate-architect",
    "destination": "https://talent.cloudemployee.io/live-job-role/digital-commerce-associate-architect",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/front-end-developer-mid-senior",
    "destination": "https://talent.cloudemployee.io/live-job-role/front-end-developer-mid-senior",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/mid-level-3d-artist",
    "destination": "https://talent.cloudemployee.io/live-job-role/mid-level-3d-artist",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/full-stack-senior-engineer-2",
    "destination": "https://talent.cloudemployee.io/live-job-role/full-stack-senior-engineer-2",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/fullstack-software-engineer2",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-software-engineer2",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/mobile-and-web-developer-react-and-react-native",
    "destination": "https://talent.cloudemployee.io/live-job-role/mobile-and-web-developer-react-and-react-native",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/data-analyst",
    "destination": "https://talent.cloudemployee.io/live-job-role/data-analyst",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/fullstack-vue-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-vue-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/consultant-e-commerce-and-technology",
    "destination": "https://talent.cloudemployee.io/live-job-role/consultant-e-commerce-and-technology",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/business-development-representative-bdr",
    "destination": "https://talent.cloudemployee.io/live-job-role/business-development-representative-bdr",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/fullstack-net-developer11",
    "destination": "https://talent.cloudemployee.io/live-job-role/fullstack-net-developer11",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/full-stack-senior-engineer001",
    "destination": "https://talent.cloudemployee.io/live-job-role/full-stack-senior-engineer001",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/junior-data-engineer-mid-level-python-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/junior-data-engineer-mid-level-python-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/ai-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/ai-engineer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/c-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/c-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/aws-devops-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/aws-devops-engineer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/machine-learning-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/machine-learning-engineer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/ios-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/ios-developer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/ui-ux-designer",
    "destination": "https://talent.cloudemployee.io/live-job-role/ui-ux-designer",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role/transformation-project-manager",
    "destination": "https://talent.cloudemployee.io/live-job-role/transformation-project-manager",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/core-ios-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/core-ios-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/core-android-developer1",
    "destination": "https://talent.cloudemployee.io/live-job-role/core-android-developer1",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/backend-software-engineer-php",
    "destination": "https://talent.cloudemployee.io/live-job-role/backend-software-engineer-php",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-dotnet-developer-85260",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-dotnet-developer-85260",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-frontend-developer-14",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-frontend-developer-14",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-frontend-developer-15",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-frontend-developer-15",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-devops-engineer-3",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-devops-engineer-3",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-data-engineer-201",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-data-engineer-201",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-backend-engineer1",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-backend-engineer1",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-azure-devops-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-azure-devops-engineer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-integrations-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-integrations-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-data-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-data-engineer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/qa-engineer1",
    "destination": "https://talent.cloudemployee.io/live-job-role/qa-engineer1",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/qa-engineer---manual-automation-technical-documentation",
    "destination": "https://talent.cloudemployee.io/live-job-role/qa-engineer---manual-automation-technical-documentation",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/scrum-master",
    "destination": "https://talent.cloudemployee.io/live-job-role/scrum-master",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-hr-business-partner",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-hr-business-partner",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-integration-backend-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-integration-backend-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-nuxt-vue-js-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-nuxt-vue-js-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-backend-api-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-backend-api-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-laravel-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-laravel-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/qa-engineer-2",
    "destination": "https://talent.cloudemployee.io/live-job-role/qa-engineer-2",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-devops-engineer-2",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-devops-engineer-2",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-fullstack-engineer-ngx8q",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-fullstack-engineer-ngx8q",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-fullstack-javascript-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-fullstack-javascript-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-ios-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-ios-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-full-stack-net-blazor-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-full-stack-net-blazor-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/qa-automation-engineer-fobdm",
    "destination": "https://talent.cloudemployee.io/live-job-role/qa-automation-engineer-fobdm",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-net-developer-with-blazor",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-net-developer-with-blazor",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-data-engineer-200",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-data-engineer-200",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-frontend-engineer-web3-next-js",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-frontend-engineer-web3-next-js",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-flutter-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-flutter-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-full-stack-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-full-stack-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-fullstack-php-laravel-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-fullstack-php-laravel-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-dotnet-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-dotnet-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/scrum-master-thdgt",
    "destination": "https://talent.cloudemployee.io/live-job-role/scrum-master-thdgt",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/sql-server-database-administrator-dba",
    "destination": "https://talent.cloudemployee.io/live-job-role/sql-server-database-administrator-dba",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-fullstack-python-developer-with-react",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-fullstack-python-developer-with-react",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-python-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-python-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-data-engineer-202",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-data-engineer-202",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/python-developer-sr-level",
    "destination": "https://talent.cloudemployee.io/live-job-role/python-developer-sr-level",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-drupal-developer011",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-drupal-developer011",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-qa-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-qa-engineer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-android-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-android-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/technical-lead",
    "destination": "https://talent.cloudemployee.io/live-job-role/technical-lead",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/solutions-architect",
    "destination": "https://talent.cloudemployee.io/live-job-role/solutions-architect",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/talent-acquisition-specialist",
    "destination": "https://talent.cloudemployee.io/live-job-role/talent-acquisition-specialist",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/software-qa-test-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/software-qa-test-engineer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/technical-customer-success-specialist",
    "destination": "https://talent.cloudemployee.io/live-job-role/technical-customer-success-specialist",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/test-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/test-engineer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/ios-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/ios-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/technical-cv-sourcing-specialist",
    "destination": "https://talent.cloudemployee.io/live-job-role/technical-cv-sourcing-specialist",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/ui-engineer-frontend-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/ui-engineer-frontend-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/solution-architect-e-commerce",
    "destination": "https://talent.cloudemployee.io/live-job-role/solution-architect-e-commerce",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/ui-ux-designer",
    "destination": "https://talent.cloudemployee.io/live-job-role/ui-ux-designer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/strategy-operations-manager",
    "destination": "https://talent.cloudemployee.io/live-job-role/strategy-operations-manager",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/transformation-project-manager",
    "destination": "https://talent.cloudemployee.io/live-job-role/transformation-project-manager",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-salesface-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-salesface-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-qa-tester-q3qlf",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-qa-tester-q3qlf",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-ui-developer-with-umbraco",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-ui-developer-with-umbraco",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-qa-tester",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-qa-tester",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-ios-developer-2-416sr",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-ios-developer-2-416sr",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/seniorteam-lead-full-stack-php-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/seniorteam-lead-full-stack-php-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-qa-tester-manual-and-automation",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-qa-tester-manual-and-automation",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/seniorlead-backend-developer",
    "destination": "https://talent.cloudemployee.io/live-job-role/seniorlead-backend-developer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-mid-fullstack-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-mid-fullstack-engineer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-software-engineer-vb6",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-software-engineer-vb6",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-quality-assurance-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-quality-assurance-engineer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/software-engineer",
    "destination": "https://talent.cloudemployee.io/live-job-role/software-engineer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-web-developer-react-wordpress",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-web-developer-react-wordpress",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/seniorlead-backend-developer-brazil",
    "destination": "https://talent.cloudemployee.io/live-job-role/seniorlead-backend-developer-brazil",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-video-editor",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-video-editor",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-technical-writer",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-technical-writer",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-salesforce-developer01",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-salesforce-developer01",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-technical-developer-php-ad-tech",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-technical-developer-php-ad-tech",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/senior-software-developer-php-laravel",
    "destination": "https://talent.cloudemployee.io/live-job-role/senior-software-developer-php-laravel",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/shopify-team-lead",
    "destination": "https://talent.cloudemployee.io/live-job-role/shopify-team-lead",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role/sr-software-eng001",
    "destination": "https://talent.cloudemployee.io/live-job-role/sr-software-eng001",
    "permanent": true
  },
  {
    "source": "/live-job-role",
    "destination": "https://talent.cloudemployee.io/",
    "permanent": true
  },
  {
    "source": "/uk/live-job-role",
    "destination": "https://talent.cloudemployee.io/",
    "permanent": true
  },
  {
    "source": "/ph/live-job-role",
    "destination": "https://talent.cloudemployee.io/",
    "permanent": true
  }
]
