// AUTO-GENERATED by scripts/scaffold/extract-redirects.ts
// Do not edit manually. Re-run the script if data/webflow/ changes.
//
// Source: data/webflow/ce-regex-redirects.json. Webflow's (.*) + %1
// syntax has been translated to Next.js :slug* path-to-regexp syntax.
import type { Redirect } from 'next/dist/lib/load-custom-routes'

export const regexRedirects: Redirect[] = [
  {
    "source": "/resources/:slug+",
    "destination": "/blog/:slug+",
    "permanent": true
  },
  {
    "source": "/customer-stories/:slug+",
    "destination": "/customer-story/:slug+",
    "permanent": true
  },
  {
    "source": "/uk/customer-stories/:slug+",
    "destination": "/uk/customer-story/:slug+",
    "permanent": true
  },
  {
    "source": "/ph/resources/:slug+",
    "destination": "/ph/blog/:slug+",
    "permanent": true
  },
  {
    "source": "/ph/customer-stories/:slug+",
    "destination": "/ph/customer-story/:slug+",
    "permanent": true
  },
  {
    "source": "/uk/resources/:slug+",
    "destination": "/uk/blog/:slug+",
    "permanent": true
  },
  {
    "source": "/developers/:slug+",
    "destination": "/technology",
    "permanent": true
  },
  {
    "source": "/tools/price-comparison-calculator",
    "destination": "/pricing",
    "permanent": true
  },
  {
    "source": "/tools/price-comparison-calculator/:slug+",
    "destination": "/pricing",
    "permanent": true
  }
]
