// AUTO-GENERATED by scripts/scaffold/extract-redirects.ts
// Do not edit manually. Re-run the script if data/webflow/ changes.
//
// Source: data/webflow/webflow-redirects.csv (tracked). The /live-job-role/*
// rows are emitted one-per-slug by scripts/scaffold/generate-job-role-redirects.ts
// into job-role-redirects.ts; this file holds the heterogeneous redirects (page
// renames, blog rollups, locale moves), preserved individually per
// docs/investigations-2026-04-23/redirects-verification.md.
//
// They are NOT collapsed into a catch-all. That is what they used to be, and the
// catch-all over-matched: Webflow has no rule for 29 of the job slugs and 404s
// them, while the catch-all redirected them into a talent-site URL that is also a
// 404. A pattern that "obviously" generalises a list is a guess about the list.
import type { Redirect } from 'next/dist/lib/load-custom-routes'

export const webflowRedirects: Redirect[] = [
  {
    "source": "/after-care",
    "destination": "/how-it-works",
    "permanent": true
  },
  {
    "source": "/back-office-pricing",
    "destination": "/pricing",
    "permanent": true
  },
  {
    "source": "/blog/it-outsourcing/how-much-does-it-cost-to-hire-a-mobile-app-developer-in-2018",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/big-data",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/b2b-lead-generation",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/aws/outsource-aws-development",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/blog/productivity/10-tips-for-effective-communication-with-a-remote-team",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/10-must-have-fitness-apps-part-1-lets-get-moving",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/11-chinese-tech-companies-you-should-know-and-why",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/7-mobile-apps-to-help-you-learn-coding-on-the-go",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/it-outsourcing/how-outsourcing-drives-startup-growth-innovation-infographic",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/it-outsourcing/benefits-of-outsourcing-through-managed-services",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/code/the-importance-of-code-reusability-in-software-development",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/5-readily-available-snacks-that-boost-brain-power",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/5-alternative-coffices-in-manila",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/it-outsourcing/why-philippines-for-business",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/20-tools-you-need-as-a-developer-in-2021",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/it-outsourcing/partnering-it-outsourcing-service-provider",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/12-startup-podcasts-for-entrepreneurs",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/6-must-watch-ted-talks-startup-founders",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/11-signs-you-lack-work-life-balance",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/10-technical-skills-to-look-for-when-hiring-devops-engineers",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/asana-vs-trello-best-project-management-tools-for-remote-working",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/how-to-create-a-compelling-github-portfolio",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/10-reasons-to-become-a-programmer",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/it-outsourcing/top-9-criteria-for-choosing-the-right-it-outsourcing-partner",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/10-challenges-faced-by-remote-developers---how-to-solve-them",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/cybersecurity-readiness-in-the-21st-century",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/15-project-management-hacks-to-increase-productivity",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/10-best-websites-to-practice-coding-online",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/it-outsourcing/top-benefits-hire-shopify-developers",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/how-important-is-your-github-activity-for-a-job-interview",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/it-outsourcing/the-5-challenges-you-will-face-when-hiring-software-developers",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/featured-uk-startup-digitalmr",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/outsourcing-as-a-way-to-boost-your-income",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/it-outsourcing/7-risks-you-will-encounter-when-hiring-freelance-developers",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/it-outsourcing/outsourcing-vs-freelance-the-pros-and-cons-to-consider",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/pokemon-go-devs-take-todays-biggest-mobile-game",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/the-future-of-drone-technology",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/programming-tips/10-best-websites-to-practice-coding-online",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/top-10-fitness-apps-beat-daily-grind",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/common-pain-points-small-business",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/top-5-interview-questions-best-answers",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/how-to-stay-motivated-at-work-when-things-become-unbearable",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/the-future-of-drone-technology",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/startup-fundraising-resources-part1",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/military-technologies",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/top-5-in-demand-digital-skills-in-the-uk",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/refer-a-candidate",
    "destination": "/for-developers",
    "permanent": true
  },
  {
    "source": "/blog/tips-to-building-and-keeping-your-dream-web-team",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/rise-of-augmented-reality-in-entertainment-development-industries",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/meet-the-team",
    "destination": "/about-us",
    "permanent": true
  },
  {
    "source": "/blog/productivity/6-apps-that-will-help-you-get-to-work",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/being-stressed-at-work",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/7-tips-eating-healthy-at-work",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/importance-of-technology-advancement-in-business-sector",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/take-regular-breaks",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/6-apps-to-train-your-brain-to",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/top-3-challenges-tech-startups-face-and-how-to-overcome-them",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/5-big-tech-trends-2017",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/7-cool-devices-to-turn-your-home-into-a-smart-home",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/women-in-tech/roundtable-conversation-about-women-in-tech-by-women-in-tech",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/11-chinese-tech-companies-you-should-know-and-why",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/uk-250m-nhs-ai-lab",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/time-management-tips-working-professionals",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/slack-channels-for-startup-ceo",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/how-to-work-with-people-you-dont-like",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/in-demand-digital-skills-in-the-uk",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/hire-fractional-devops-engineers",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/blog/top-benefits-hire-shopify-developers",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/productivity/onboarding-mistakes-why-new-hires-quit",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/non-tech-founders-of-big-tech-companies",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/programming-tips/front-end-and-back-end-developers-a-quick-comparison",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/inside-microsofts-london-flagship-store",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/eric-dalius-artificial-intelligence-has-a-huge-impact-on-startup-businesses",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/hire-fractional-qa-tester",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/ios",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/old-home-2",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/posts-categories/tech-news",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/write-for-us",
    "destination": "/contact",
    "permanent": true
  },
  {
    "source": "/our-expertise",
    "destination": "/how-it-works",
    "permanent": true
  },
  {
    "source": "/html5",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/client-faq",
    "destination": "/how-it-works",
    "permanent": true
  },
  {
    "source": "/blog-classic",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/our-technologies",
    "destination": "/how-it-works",
    "permanent": true
  },
  {
    "source": "/get-in-touch",
    "destination": "/contact",
    "permanent": true
  },
  {
    "source": "/talents/hire-dot-net-developers",
    "destination": "/start-hiring",
    "permanent": true
  },
  {
    "source": "/blog-sidebar",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/posts-categories/productivity",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/hire",
    "destination": "/start-hiring",
    "permanent": true
  },
  {
    "source": "/contact-us",
    "destination": "/contact",
    "permanent": true
  },
  {
    "source": "/life-beyond-offshoring",
    "destination": "/about-us",
    "permanent": true
  },
  {
    "source": "/uk/home-alternate",
    "destination": "/uk",
    "permanent": true
  },
  {
    "source": "/why-the-philippines",
    "destination": "/how-it-works",
    "permanent": true
  },
  {
    "source": "/insights",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/au/home",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/careers-new",
    "destination": "/for-developers",
    "permanent": true
  },
  {
    "source": "/careers",
    "destination": "/for-developers",
    "permanent": true
  },
  {
    "source": "/why-cloud-employee",
    "destination": "/about-us",
    "permanent": true
  },
  {
    "source": "/contact-us-2",
    "destination": "/contact",
    "permanent": true
  },
  {
    "source": "/leadership",
    "destination": "/about-us",
    "permanent": true
  },
  {
    "source": "/privacy-policy",
    "destination": "/legals/privacy-policy",
    "permanent": true
  },
  {
    "source": "/salesforce/dedicated-salesforce-developer",
    "destination": "/start-hiring",
    "permanent": true
  },
  {
    "source": "/why-our-model-works",
    "destination": "/how-it-works",
    "permanent": true
  },
  {
    "source": "/developer-pricing",
    "destination": "/pricing",
    "permanent": true
  },
  {
    "source": "/uk/client-faq",
    "destination": "/uk/how-it-works",
    "permanent": true
  },
  {
    "source": "/ui-ux/hire-ui-ux-developers",
    "destination": "/start-hiring",
    "permanent": true
  },
  {
    "source": "/our-story",
    "destination": "/about-us",
    "permanent": true
  },
  {
    "source": "/life-at-cloud-employee",
    "destination": "/about-us",
    "permanent": true
  },
  {
    "source": "/uk/home",
    "destination": "/uk",
    "permanent": true
  },
  {
    "source": "/au/how-it-works",
    "destination": "/how-it-works",
    "permanent": true
  },
  {
    "source": "/start-hiring",
    "destination": "/start-hiring/contact-info",
    "permanent": true
  },
  {
    "source": "/email-link",
    "destination": "/book-a-call",
    "permanent": true
  },
  {
    "source": "/hire/cloud-engineers",
    "destination": "/services/cloud-engineers",
    "permanent": true
  },
  {
    "source": "/hire-software-developers-philippines",
    "destination": "/hire/philippines-offshoring",
    "permanent": true
  },
  {
    "source": "/hire/philippines-offshoring",
    "destination": "/services/filipino-developers",
    "permanent": true
  },
  {
    "source": "/hire/devops-engineers",
    "destination": "/services/devops-engineers",
    "permanent": true
  },
  {
    "source": "/hire/data-scientists",
    "destination": "/services/data-scientists",
    "permanent": true
  },
  {
    "source": "/hire-csharp-developers",
    "destination": "/technology/csharp",
    "permanent": true
  },
  {
    "source": "/ph/start-hiring-now",
    "destination": "/ph/start-hiring/get-started",
    "permanent": true
  },
  {
    "source": "/hire/qa-analysts-testers",
    "destination": "/services/qa-analysts-testers",
    "permanent": true
  },
  {
    "source": "/hire-virtual-assistants",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/hire/software-engineers",
    "destination": "/services/software-engineers",
    "permanent": true
  },
  {
    "source": "/hire/technical-architects",
    "destination": "/services",
    "permanent": true
  },
  {
    "source": "/hire/front-end-developers",
    "destination": "/services/front-end-developers",
    "permanent": true
  },
  {
    "source": "/hire/back-end-developers",
    "destination": "/services/back-end-developers",
    "permanent": true
  },
  {
    "source": "/uk/start-hiring-now",
    "destination": "/uk/start-hiring/get-started",
    "permanent": true
  },
  {
    "source": "/hire-angular-developers",
    "destination": "/technology/angular",
    "permanent": true
  },
  {
    "source": "/hire/full-stack-developers",
    "destination": "/services/full-stack-developers",
    "permanent": true
  },
  {
    "source": "/hire/latam-nearshoring",
    "destination": "/services/latam-developers",
    "permanent": true
  },
  {
    "source": "/hire/no-code-developers",
    "destination": "/services/no-code-developers",
    "permanent": true
  },
  {
    "source": "/hire/mobile-developers",
    "destination": "/services/mobile-developers",
    "permanent": true
  },
  {
    "source": "/hire/ai-engineers",
    "destination": "/services/ai-engineers",
    "permanent": true
  },
  {
    "source": "/hire-php-developers",
    "destination": "/technology/php",
    "permanent": true
  },
  {
    "source": "/hire-admin-staff-philippines",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/start-hiring-now",
    "destination": "/start-hiring/contact-info",
    "permanent": true
  },
  {
    "source": "/uk/hire/ai-engineers",
    "destination": "/uk/services/ai-engineers",
    "permanent": true
  },
  {
    "source": "/uk/hire/philippines-offshoring",
    "destination": "/uk/services/filipino-developers",
    "permanent": true
  },
  {
    "source": "/resources/(.*)",
    "destination": "/blog/%1",
    "permanent": true
  },
  {
    "source": "/uk/hire/technical-architects",
    "destination": "/uk/services",
    "permanent": true
  },
  {
    "source": "/uk/resources/the-reality-of-modern-tech-recruitment-a-broken-system",
    "destination": "/uk/blog/the-reality-of-modern-tech-recruitment-a-broken-system",
    "permanent": true
  },
  {
    "source": "/uk/hire/qa-analysts-testers",
    "destination": "/uk/services/qa-analysts-testers",
    "permanent": true
  },
  {
    "source": "/uk/inital-assessment",
    "destination": "/uk/initial-assessment",
    "permanent": true
  },
  {
    "source": "/resources",
    "destination": "/downloads",
    "permanent": true
  },
  {
    "source": "/uk/free-downloads",
    "destination": "/uk/downloads",
    "permanent": true
  },
  {
    "source": "/uk/book-a-cto-consultation",
    "destination": "/uk/book-anto",
    "permanent": true
  },
  {
    "source": "/uk/hire/latam-nearshoring",
    "destination": "/uk/services/latam-developers",
    "permanent": true
  },
  {
    "source": "/uk/tools-quizzes",
    "destination": "/uk/tools",
    "permanent": true
  },
  {
    "source": "/uk/team",
    "destination": "/uk/about-us",
    "permanent": true
  },
  {
    "source": "/resources/the-reality-of-modern-tech-recruitment-a-broken-system",
    "destination": "/blog/the-reality-of-modern-tech-recruitment-a-broken-system",
    "permanent": true
  },
  {
    "source": "/resources/freelancers-vs-cloud-employee",
    "destination": "/blog/freelancers-vs-cloud-employee",
    "permanent": true
  },
  {
    "source": "/customer-stories/event-connections",
    "destination": "/customer-story/event-connections",
    "permanent": true
  },
  {
    "source": "/uk/hire/data-scientists",
    "destination": "/uk/services/data-scientists",
    "permanent": true
  },
  {
    "source": "/uk/hire/mobile-developers",
    "destination": "/uk/services/mobile-developers",
    "permanent": true
  },
  {
    "source": "/uk/hire/front-end-developers",
    "destination": "/uk/services/front-end-developers",
    "permanent": true
  },
  {
    "source": "/resources/7-benefits-of-outsourcing-web-development-for-startups",
    "destination": "/blog/7-benefits-of-outsourcing-web-development-for-startups",
    "permanent": true
  },
  {
    "source": "/free-downloads",
    "destination": "/downloads",
    "permanent": true
  },
  {
    "source": "/uk/hire/cloud-engineers",
    "destination": "/uk/services/cloud-engineers",
    "permanent": true
  },
  {
    "source": "/book-a-cto-consultation",
    "destination": "/book-anto",
    "permanent": true
  },
  {
    "source": "/uk/hire/devops-engineers",
    "destination": "/uk/services/devops-engineers",
    "permanent": true
  },
  {
    "source": "/inital-assessment",
    "destination": "/initial-assessment",
    "permanent": true
  },
  {
    "source": "/resources/cto-profile-meet-des-matthewson",
    "destination": "/blog/cto-profile-meet-des-matthewson",
    "permanent": true
  },
  {
    "source": "/uk/hire/no-code-developers",
    "destination": "/uk/services/no-code-developers",
    "permanent": true
  },
  {
    "source": "/uk/customer-stories/salmon-software",
    "destination": "/uk/customer-story/salmon-software",
    "permanent": true
  },
  {
    "source": "/resources/data-engineer-vs-data-scientist-vs-ai-engineer-key-differences-demand-drivers-and-how-to-hire-right",
    "destination": "/blog/data-engineer-vs-data-scientist-vs-ai-engineer-key-differences-demand-drivers-and-how-to-hire-right",
    "permanent": true
  },
  {
    "source": "/customer-stories/(.*)",
    "destination": "/customer-story/%1",
    "permanent": true
  },
  {
    "source": "/resources/how-staff-augmentation-is-rewriting-the-rules-of-software-development-speed-and-efficiency",
    "destination": "/blog/how-staff-augmentation-is-rewriting-the-rules-of-software-development-speed-and-efficiency",
    "permanent": true
  },
  {
    "source": "/resources/staff-augmentation-vs-consulting-outsourcing-and-managed-services",
    "destination": "/blog/staff-augmentation-vs-consulting-outsourcing-and-managed-services",
    "permanent": true
  },
  {
    "source": "/uk/customer-stories/event-connections",
    "destination": "/uk/customer-story/event-connections",
    "permanent": true
  },
  {
    "source": "/customer-stories/salmon-software",
    "destination": "/customer-story/salmon-software",
    "permanent": true
  },
  {
    "source": "/uk/hire/software-engineers",
    "destination": "/uk/services/software-engineers",
    "permanent": true
  },
  {
    "source": "/industry-guide/cto-profile-meet-des-matthewson",
    "destination": "/scaling-teams/cto-profile-meet-des-matthewson",
    "permanent": true
  },
  {
    "source": "/uk/hire/back-end-developers",
    "destination": "/uk/services/back-end-developers",
    "permanent": true
  },
  {
    "source": "/tools-quizzes",
    "destination": "/tools",
    "permanent": true
  },
  {
    "source": "/uk/hire/full-stack-developers",
    "destination": "/uk/services/full-stack-developers",
    "permanent": true
  },
  {
    "source": "/industry-guide/scaling-product-development-with-remote-software-developers",
    "destination": "/scaling-teams/scaling-product-development-with-remote-software-developers",
    "permanent": true
  },
  {
    "source": "/resources/securing-ai-the-ctos-guide-to-validation-and-minimum-safety-standards",
    "destination": "/blog/securing-ai-the-ctos-guide-to-validation-and-minimum-safety-standards",
    "permanent": true
  },
  {
    "source": "/ph/hire/devops-engineers",
    "destination": "/ph/services/devops-engineers",
    "permanent": true
  },
  {
    "source": "/uk/industry-guide/cto-profile-meet-des-matthewson",
    "destination": "/uk/scaling-teams/cto-profile-meet-des-matthewson",
    "permanent": true
  },
  {
    "source": "/ph/hire/qa-analysts-testers",
    "destination": "/ph/services/qa-analysts-testers",
    "permanent": true
  },
  {
    "source": "/ph/hire/software-engineers",
    "destination": "/ph/services/software-engineers",
    "permanent": true
  },
  {
    "source": "/ph/customer-stories/salmon-software",
    "destination": "/ph/customer-story/salmon-software",
    "permanent": true
  },
  {
    "source": "/uk/resources/freelancers-vs-cloud-employee",
    "destination": "/uk/blog/freelancers-vs-cloud-employee",
    "permanent": true
  },
  {
    "source": "/ph/free-downloads",
    "destination": "/ph/downloads",
    "permanent": true
  },
  {
    "source": "/ph/resources/cto-profile-meet-des-matthewson",
    "destination": "/ph/blog/cto-profile-meet-des-matthewson",
    "permanent": true
  },
  {
    "source": "/ph/hire/ai-engineers",
    "destination": "/ph/services/ai-engineers",
    "permanent": true
  },
  {
    "source": "/ph/hire/full-stack-developers",
    "destination": "/ph/services/full-stack-developers",
    "permanent": true
  },
  {
    "source": "/ph/inital-assessment",
    "destination": "/ph/initial-assessment",
    "permanent": true
  },
  {
    "source": "/uk/resources/7-benefits-of-outsourcing-web-development-for-startups",
    "destination": "/uk/blog/7-benefits-of-outsourcing-web-development-for-startups",
    "permanent": true
  },
  {
    "source": "/uk/resources/how-staff-augmentation-is-rewriting-the-rules-of-software-development-speed-and-efficiency",
    "destination": "/uk/blog/how-staff-augmentation-is-rewriting-the-rules-of-software-development-speed-and-efficiency",
    "permanent": true
  },
  {
    "source": "/ph/team",
    "destination": "/ph/about-us",
    "permanent": true
  },
  {
    "source": "/ph/resources/data-engineer-vs-data-scientist-vs-ai-engineer-key-differences-demand-drivers-and-how-to-hire-right",
    "destination": "/ph/blog/data-engineer-vs-data-scientist-vs-ai-engineer-key-differences-demand-drivers-and-how-to-hire-right",
    "permanent": true
  },
  {
    "source": "/ph/hire/back-end-developers",
    "destination": "/ph/services/back-end-developers",
    "permanent": true
  },
  {
    "source": "/ph/resources/how-staff-augmentation-is-rewriting-the-rules-of-software-development-speed-and-efficiency",
    "destination": "/ph/blog/how-staff-augmentation-is-rewriting-the-rules-of-software-development-speed-and-efficiency",
    "permanent": true
  },
  {
    "source": "/ph/resources/freelancers-vs-cloud-employee",
    "destination": "/ph/blog/freelancers-vs-cloud-employee",
    "permanent": true
  },
  {
    "source": "/ph/resources",
    "destination": "/ph/downloads",
    "permanent": true
  },
  {
    "source": "/uk/resources",
    "destination": "/uk/downloads",
    "permanent": true
  },
  {
    "source": "/ph/hire/mobile-developers",
    "destination": "/ph/services/mobile-developers",
    "permanent": true
  },
  {
    "source": "/ph/hire/latam-nearshoring",
    "destination": "/ph/services/latam-developers",
    "permanent": true
  },
  {
    "source": "/ph/hire/technical-architects",
    "destination": "/ph/services",
    "permanent": true
  },
  {
    "source": "/uk/customer-stories/(.*)",
    "destination": "/uk/customer-story/%1",
    "permanent": true
  },
  {
    "source": "/ph/hire/cloud-engineers",
    "destination": "/ph/services/cloud-engineers",
    "permanent": true
  },
  {
    "source": "/ph/resources/(.*)",
    "destination": "/ph/blog/%1",
    "permanent": true
  },
  {
    "source": "/ph/customer-stories/(.*)",
    "destination": "/ph/customer-story/%1",
    "permanent": true
  },
  {
    "source": "/uk/resources/securing-ai-the-ctos-guide-to-validation-and-minimum-safety-standards",
    "destination": "/uk/blog/securing-ai-the-ctos-guide-to-validation-and-minimum-safety-standards",
    "permanent": true
  },
  {
    "source": "/ph/tools-quizzes",
    "destination": "/ph/tools",
    "permanent": true
  },
  {
    "source": "/ph/resources/the-reality-of-modern-tech-recruitment-a-broken-system",
    "destination": "/ph/blog/the-reality-of-modern-tech-recruitment-a-broken-system",
    "permanent": true
  },
  {
    "source": "/ph/hire/front-end-developers",
    "destination": "/ph/services/front-end-developers",
    "permanent": true
  },
  {
    "source": "/uk/resources/cto-profile-meet-des-matthewson",
    "destination": "/uk/blog/cto-profile-meet-des-matthewson",
    "permanent": true
  },
  {
    "source": "/uk/resources/data-engineer-vs-data-scientist-vs-ai-engineer-key-differences-demand-drivers-and-how-to-hire-right",
    "destination": "/uk/blog/data-engineer-vs-data-scientist-vs-ai-engineer-key-differences-demand-drivers-and-how-to-hire-right",
    "permanent": true
  },
  {
    "source": "/uk/resources/(.*)",
    "destination": "/uk/blog/%1",
    "permanent": true
  },
  {
    "source": "/ph/resources/staff-augmentation-vs-consulting-outsourcing-and-managed-services",
    "destination": "/ph/blog/staff-augmentation-vs-consulting-outsourcing-and-managed-services",
    "permanent": true
  },
  {
    "source": "/uk/resources/staff-augmentation-vs-consulting-outsourcing-and-managed-services",
    "destination": "/uk/blog/staff-augmentation-vs-consulting-outsourcing-and-managed-services",
    "permanent": true
  },
  {
    "source": "/ph/book-a-cto-consultation",
    "destination": "/ph/book-anto",
    "permanent": true
  },
  {
    "source": "/ph/hire/philippines-offshoring",
    "destination": "/ph/services/filipino-developers",
    "permanent": true
  },
  {
    "source": "/uk/industry-guide/scaling-product-development-with-remote-software-developers",
    "destination": "/uk/scaling-teams/scaling-product-development-with-remote-software-developers",
    "permanent": true
  },
  {
    "source": "/ph/resources/7-benefits-of-outsourcing-web-development-for-startups",
    "destination": "/ph/blog/7-benefits-of-outsourcing-web-development-for-startups",
    "permanent": true
  },
  {
    "source": "/ph/hire/data-scientists",
    "destination": "/ph/services/data-scientists",
    "permanent": true
  },
  {
    "source": "/ph/hire/no-code-developers",
    "destination": "/ph/services/no-code-developers",
    "permanent": true
  },
  {
    "source": "/ph/resources/securing-ai-the-ctos-guide-to-validation-and-minimum-safety-standards",
    "destination": "/ph/blog/securing-ai-the-ctos-guide-to-validation-and-minimum-safety-standards",
    "permanent": true
  },
  {
    "source": "/ph/customer-stories/event-connections",
    "destination": "/ph/customer-story/event-connections",
    "permanent": true
  },
  {
    "source": "/ph/industry-guide/cto-profile-meet-des-matthewson",
    "destination": "/ph/scaling-teams/cto-profile-meet-des-matthewson",
    "permanent": true
  },
  {
    "source": "/ph/industry-guide/scaling-product-development-with-remote-software-developers",
    "destination": "/ph/scaling-teams/scaling-product-development-with-remote-software-developers",
    "permanent": true
  },
  {
    "source": "/cloudemployeereviews",
    "destination": "/reviews",
    "permanent": true
  },
  {
    "source": "/cloudemployeereviews/clean-link",
    "destination": "/reviews/cleanlink-software-ltd",
    "permanent": true
  },
  {
    "source": "/tools/self-assessment",
    "destination": "/self-assessment",
    "permanent": true
  },
  {
    "source": "/tools/thank-you-psychometric-test",
    "destination": "/thank-you-psychometric-test",
    "permanent": true
  },
  {
    "source": "/psychometric-test",
    "destination": "/tools/free-psychometric-test",
    "permanent": true
  },
  {
    "source": "/customer-stories/travel-tech-client",
    "destination": "/customer-story/travel-tech-client",
    "permanent": true
  },
  {
    "source": "/uk/customer-stories/travel-tech-client",
    "destination": "/uk/customer-story/travel-tech-client",
    "permanent": true
  },
  {
    "source": "/ph/customer-stories/travel-tech-client",
    "destination": "/ph/customer-story/travel-tech-client",
    "permanent": true
  },
  {
    "source": "/customer-stories/willo",
    "destination": "/customer-story/willo",
    "permanent": true
  },
  {
    "source": "/uk/customer-stories/willo",
    "destination": "/uk/customer-story/willo",
    "permanent": true
  },
  {
    "source": "/ph/customer-stories/willo",
    "destination": "/ph/customer-story/willo",
    "permanent": true
  },
  {
    "source": "/book-seb",
    "destination": "/book-a-call/seb",
    "permanent": true
  },
  {
    "source": "/uk/book-seb",
    "destination": "/uk/book-a-call/seb",
    "permanent": true
  },
  {
    "source": "/ph/book-seb",
    "destination": "/ph/book-a-call/seb",
    "permanent": true
  },
  {
    "source": "/book-anto",
    "destination": "/book-a-call/anto",
    "permanent": true
  },
  {
    "source": "/uk/book-anto",
    "destination": "/uk/book-a-call/anto",
    "permanent": true
  },
  {
    "source": "/ph/book-anto",
    "destination": "/ph/book-a-call/anto",
    "permanent": true
  },
  {
    "source": "/pricing-old",
    "destination": "/pricing",
    "permanent": true
  },
  {
    "source": "/uk/pricing-old",
    "destination": "/uk/pricing",
    "permanent": true
  },
  {
    "source": "/book-a-call/steph",
    "destination": "/book-a-call/stephanie",
    "permanent": true
  },
  {
    "source": "/developers",
    "destination": "/technology",
    "permanent": true
  },
  {
    "source": "/developers/(.*)",
    "destination": "/technology",
    "permanent": true
  },
  {
    "source": "/archive/pricing-old",
    "destination": "/pricing",
    "permanent": true
  },
  {
    "source": "/uk/archive/pricing-old",
    "destination": "/uk/pricing",
    "permanent": true
  },
  {
    "source": "/blog/freelancers-vs-cloud-employee",
    "destination": "/compare/freelancers",
    "permanent": true
  },
  {
    "source": "/blog/our-proven-model-for-onboarding-software-developers",
    "destination": "/hiring-tips/our-proven-model-for-onboarding-software-developers",
    "permanent": true
  },
  {
    "source": "/blog/7-benefits-of-outsourcing-web-development-for-startups",
    "destination": "/nearshoring-offshoring/7-benefits-of-outsourcing-web-development-for-startups",
    "permanent": true
  },
  {
    "source": "/blog/how-staff-augmentation-is-rewriting-the-rules-of-software-development-speed-and-efficiency",
    "destination": "/staff-augmentation/how-staff-augmentation-is-rewriting-the-rules-of-software-development-speed-and-efficiency",
    "permanent": true
  },
  {
    "source": "/uk/blog/how-staff-augmentation-is-rewriting-the-rules-of-software-development-speed-and-efficiency",
    "destination": "/uk/staff-augmentation/how-staff-augmentation-is-rewriting-the-rules-of-software-development-speed-and-efficiency",
    "permanent": true
  },
  {
    "source": "/book-a-call/brooke",
    "destination": "/book-a-call",
    "permanent": true
  },
  {
    "source": "/team/brooke-melidoni",
    "destination": "/about-us",
    "permanent": true
  },
  {
    "source": "/thank-you-psychometric-test",
    "destination": "/thank-you-culture-match",
    "permanent": true
  },
  {
    "source": "/tools/free-psychometric-test",
    "destination": "/tools/culture-match",
    "permanent": true
  },
  {
    "source": "/services/filipino-developers",
    "destination": "/services/philippines-developers",
    "permanent": true
  },
  {
    "source": "/uk/services/filipino-developers",
    "destination": "/uk/services/philippines-developers",
    "permanent": true
  },
  {
    "source": "/ph/services/filipino-developers",
    "destination": "/ph/services/philippines-developers",
    "permanent": true
  },
  {
    "source": "/impact",
    "destination": "/our-work",
    "permanent": true
  },
  {
    "source": "/uk/impact",
    "destination": "/uk/our-work",
    "permanent": true
  },
  {
    "source": "/ph/impact",
    "destination": "/ph/our-work",
    "permanent": true
  },
  {
    "source": "/retain",
    "destination": "/how-it-works",
    "permanent": true
  },
  {
    "source": "/embed",
    "destination": "/how-it-works",
    "permanent": true
  },
  {
    "source": "/source",
    "destination": "/how-it-works",
    "permanent": true
  },
  {
    "source": "/sourced",
    "destination": "/how-it-works",
    "permanent": true
  },
  {
    "source": "/blog/programming-tips/best-mobile-game-engines-2018",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/hire-android-developers",
    "destination": "/services/android-developers",
    "permanent": true
  },
  {
    "source": "/hire-javascript-developers",
    "destination": "/services/front-end-developers",
    "permanent": true
  },
  {
    "source": "/blog/it-",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/it-outsourcing/build-a-close-relationship-with-offshore-team",
    "destination": "/nearshoring-offshoring",
    "permanent": true
  },
  {
    "source": "/blog/productivity/how-important-is-your-github-activity-for-a-job-interview",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/programming-tips/7-mobile-apps-to-help-you-learn-coding-on-the-go",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/blog/tech-news/featured-uk-startup-netpeak-software",
    "destination": "/blog",
    "permanent": true
  },
  {
    "source": "/technology/angular",
    "destination": "/technology/angular-developers",
    "permanent": true
  },
  {
    "source": "/hire-etl-developers",
    "destination": "/services/data-scientists",
    "permanent": true
  },
  {
    "source": "/technology/csharp",
    "destination": "/technology/csharp-developers",
    "permanent": true
  },
  {
    "source": "/uk/technology/kotlin",
    "destination": "/uk/technology/kotlin-developers",
    "permanent": true
  },
  {
    "source": "/ph/%",
    "destination": "https://talent.cloudemployee.io/",
    "permanent": true
  },
  {
    "source": "/ph",
    "destination": "https://talent.cloudemployee.io/",
    "permanent": true
  },
  {
    "source": "/careers/backend-python-developer",
    "destination": "/technology/python-developers",
    "permanent": true
  },
  {
    "source": "/compare/cloud-employee-vs-arc-dev",
    "destination": "/compare",
    "permanent": true
  },
  {
    "source": "/compare/cloud-employee-vs-revelo",
    "destination": "/compare",
    "permanent": true
  },
  {
    "source": "/compare/cloud-employee-vs-toptal",
    "destination": "/compare",
    "permanent": true
  },
  {
    "source": "/compare/dev-agencies",
    "destination": "/compare",
    "permanent": true
  },
  {
    "source": "/download/our-internal-hiring-sop",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/download/the-ctos-hiring-framework",
    "destination": "/downloads",
    "permanent": true
  },
  {
    "source": "/download/weekly-self-reporting-system",
    "destination": "/downloads",
    "permanent": true
  },
  {
    "source": "/hiring-tips/how-to-hire-python-developers",
    "destination": "/hiring-tips",
    "permanent": true
  },
  {
    "source": "/managing-engineers/software-developer-performance-metrics-for-ctos",
    "destination": "/managing-engineers",
    "permanent": true
  },
  {
    "source": "/reviews/cameron-pearson",
    "destination": "/reviews",
    "permanent": true
  },
  {
    "source": "/reviews/emsl",
    "destination": "/reviews",
    "permanent": true
  },
  {
    "source": "/reviews/mercato",
    "destination": "/reviews",
    "permanent": true
  },
  {
    "source": "/scaling-teams/scaling-product-development-with-remote-software-developers",
    "destination": "/scaling-teams",
    "permanent": true
  },
  {
    "source": "/start-hiring/get-started",
    "destination": "/start-hiring/contact-info",
    "permanent": true
  },
  {
    "source": "/technology/cloudwatch",
    "destination": "/technology",
    "permanent": true
  },
  {
    "source": "/technology/go-developers",
    "destination": "/technology",
    "permanent": true
  },
  {
    "source": "/technology/postgresql",
    "destination": "/technology",
    "permanent": true
  },
  {
    "source": "/technology/snowflake",
    "destination": "/technology",
    "permanent": true
  },
  {
    "source": "/technology/vuejs-developers",
    "destination": "/technology",
    "permanent": true
  },
  {
    "source": "/videos/embedded-talent",
    "destination": "/videos",
    "permanent": true
  },
  {
    "source": "/videos/hire-nearshore-developers-that-feel-in-house-from-day-one",
    "destination": "/videos",
    "permanent": true
  },
  {
    "source": "/videos/how-to-embed-top-global-developers-into-your-business",
    "destination": "/videos",
    "permanent": true
  },
  {
    "source": "/videos/how-to-hire-top-developers-in-7-days",
    "destination": "/videos",
    "permanent": true
  },
  {
    "source": "/videos/learning-development",
    "destination": "/videos",
    "permanent": true
  },
  {
    "source": "/videos/onboarding-team",
    "destination": "/videos",
    "permanent": true
  },
  {
    "source": "/videos/scalable-recruitment",
    "destination": "/videos",
    "permanent": true
  },
  {
    "source": "/videos/talent-retention",
    "destination": "/videos",
    "permanent": true
  },
  {
    "source": "/videos/talent-success-team",
    "destination": "/videos",
    "permanent": true
  },
  {
    "source": "/videos/wellness",
    "destination": "/videos",
    "permanent": true
  },
  {
    "source": "/tools/price-comparison-calculator(.*)",
    "destination": "/pricing",
    "permanent": true
  },
  {
    "source": "/tools/price-comparison-calculator",
    "destination": "/pricing",
    "permanent": true
  }
]
