// HARD GATE: studio/schemas/objects/portable-text.ts videoEmbed + table types
// MUST be deployed to production Sanity BEFORE this migrator runs. Studio
// rejects writes carrying unknown _type values; if the deploy hasn't landed,
// every .commit() will throw. See PHASE_HISTORY CONTENT-1E entry.
//
// CONTENT-1E — Webflow w-embed recovery migrator.
//
// Re-runs the upgraded toPortableText (Step 3) against Webflow source HTML
// for the 3 affected (type, field) pairs:
//   - blogPost.content           (115 embeds across 58 docs)
//   - compareBlog.content        (49 embeds across 27 docs)
//   - customerStory.hiringNeedsTable  (3 embeds across 3 docs)
//
// technology + service: ZERO embeds per Step 1 sweep; skipped at the spec
// level. A drift-detector check at end of run halts if a future sweep finds
// embeds in those types (catches CE adding embed content later).
//
// Per-doc guard sequence (halt-on-first-failure per CONTENT-1D-CLEANUP):
//   1. Sanity doc fetched by exact _id; _type matches expected type.
//   2. Pre-patch snapshot of the target field written to
//      audit-output/content-1e/pre-patch-snapshots/ (OVERRIDE 2 — rollback
//      escape hatch).
//   3. Webflow source item resolved by webflowId (extracted from _id).
//   4. Webflow source field is a non-empty string.
//   5. Deserializer output carries >= sweep-expected videoEmbed+table count.
//   6. Atomic .patch.set({ [field]: newPortableText }).commit().
//
// Idempotency:
//   - videoEmbed/table _keys are deterministic (`{type}-{webflowId}-{pos}`).
//   - Plain `block` _keys + link `markDefs` IDs are regenerated by
//     @sanity/block-tools on each run (pre-existing block-tools behavior).
//   - Semantic content is identical across re-runs; Sanity sees content[]
//     array replaced on each pass. Verifier matches structurally, not by
//     _key.
//
// Run: npx tsx scripts/content/migrate-w-embed-recovery.ts

import fs from 'node:fs'
import path from 'node:path'

import { ensureWebflow } from '@/lib/env'
import { sanityWriteClient } from '@/lib/content/sanity-write-client'
import { getCollectionItems, type WebflowItem } from '@/lib/content/webflow-read-client'
import { CE_BLOG_COLLECTIONS, CE_COLLECTION_IDS } from '@/lib/content/ce-collection-ids'
import { toPortableText } from '@/lib/content/migration-helpers'
import { recordMigration } from '@/lib/content/migration-tracker'

ensureWebflow()

type DocType = 'blogPost' | 'compareBlog' | 'customerStory'

type SweepEntry = {
  docId: string
  slug: string | null
  docType: 'blogPost' | 'compareBlog' | 'technology' | 'service' | 'customerStory'
  collectionSlug: string
  fieldName: string
  wrapperKind: string
  position: number
  embedType: string
}

type Spec = {
  docType: DocType
  // Sanity-side field name to rewrite.
  sanityField: 'content' | 'hiringNeedsTable'
  // Webflow-side field name (RichText source).
  webflowField: 'content' | 'hiring-needs-table'
  // Webflow source collection IDs to scan for matching items.
  sourceCollectionIds: string[]
}

const SPECS: Spec[] = [
  {
    docType: 'blogPost',
    sanityField: 'content',
    webflowField: 'content',
    sourceCollectionIds: CE_BLOG_COLLECTIONS.map((c) => c.id),
  },
  {
    docType: 'compareBlog',
    sanityField: 'content',
    webflowField: 'content',
    sourceCollectionIds: [CE_COLLECTION_IDS.compareBlogs],
  },
  {
    docType: 'customerStory',
    sanityField: 'hiringNeedsTable',
    webflowField: 'hiring-needs-table',
    sourceCollectionIds: [CE_COLLECTION_IDS.customerStories],
  },
]

const SWEEP_INVENTORY_FILE = path.resolve('audit-output/content-1e/w-embed-sweep-inventory.json')
const SNAPSHOT_DIR = path.resolve('audit-output/content-1e/pre-patch-snapshots')

// ---------------------------------------------------------------
// Pre-flight helpers
// ---------------------------------------------------------------

function loadSweepInventory(): {
  byDoc: Map<string, SweepEntry[]>
  totals: { sourceTotal: number; technologyCount: number; serviceCount: number }
} {
  if (!fs.existsSync(SWEEP_INVENTORY_FILE)) {
    throw new Error(
      `Sweep inventory missing at ${SWEEP_INVENTORY_FILE}. Run scripts/content/probe-w-embed-sweep.ts first.`,
    )
  }
  const raw = fs.readFileSync(SWEEP_INVENTORY_FILE, 'utf-8')
  const data = JSON.parse(raw) as { entries: SweepEntry[] }
  const byDoc = new Map<string, SweepEntry[]>()
  let technologyCount = 0
  let serviceCount = 0
  for (const e of data.entries) {
    if (e.docType === 'technology') technologyCount++
    if (e.docType === 'service') serviceCount++
    const list = byDoc.get(e.docId) ?? []
    list.push(e)
    byDoc.set(e.docId, list)
  }
  return {
    byDoc,
    totals: { sourceTotal: data.entries.length, technologyCount, serviceCount },
  }
}

// Classify sweep-target docs by whether the Sanity doc exists:
//   - existsInSanity: patch normally.
//   - dedupedToCanonical: a sibling Sanity doc with the same slug exists.
//     CONTENT-1C deduplicated multi-collection blog mirrors; the canonical
//     gets patched from its own Webflow source. Skip with log (not an error).
//   - orphan: no Sanity doc at this _id AND no slug-canonical. HALT — this
//     is unrecovered content, not deduplication.
async function classifySweepTargets(docs: Map<string, { slug: string | null; type: string }>) {
  const sanityRows = await sanityWriteClient.fetch<Array<{ _id: string; slug: string | null }>>(
    `*[_type in ["blogPost","compareBlog","customerStory"] && !(_id match "smoke-test-*")]{_id, "slug": slug.current}`,
  )
  const sanityById = new Set(sanityRows.map((r) => r._id))
  const sanityBySlug = new Map<string, string[]>()
  for (const r of sanityRows) {
    if (!r.slug) continue
    const arr = sanityBySlug.get(r.slug) ?? []
    arr.push(r._id)
    sanityBySlug.set(r.slug, arr)
  }
  const existing: string[] = []
  const deduped: Array<{ docId: string; slug: string; canonicalIds: string[] }> = []
  const orphans: Array<{ docId: string; slug: string | null }> = []
  for (const [docId, info] of docs) {
    if (sanityById.has(docId)) {
      existing.push(docId)
      continue
    }
    const canonicals = info.slug ? sanityBySlug.get(info.slug) ?? [] : []
    if (canonicals.length > 0 && info.slug) {
      deduped.push({ docId, slug: info.slug, canonicalIds: canonicals })
    } else {
      orphans.push({ docId, slug: info.slug })
    }
  }
  return { existing: new Set(existing), deduped, orphans }
}

async function buildWebflowSource(specs: Spec[]): Promise<Map<string, WebflowItem>> {
  const all = new Set<string>()
  for (const s of specs) for (const cid of s.sourceCollectionIds) all.add(cid)
  const map = new Map<string, WebflowItem>()
  for (const cid of all) {
    const items = await getCollectionItems(cid)
    for (const it of items) {
      // Multi-collection blogPost: items may appear in more than one collection.
      // Latest-write wins is fine for our needs — RichText source field is
      // the same across mirrors.
      map.set(it.id, it)
    }
  }
  return map
}

function snapshotFilename(docType: DocType, slug: string | null, webflowId: string): string {
  const safe = (slug ?? 'no-slug').replace(/[^a-z0-9-]/gi, '_').slice(0, 80)
  const shortId = webflowId.slice(-6)
  return path.join(SNAPSHOT_DIR, `${docType}-${safe}-${shortId}.json`)
}

// ---------------------------------------------------------------
// Main
// ---------------------------------------------------------------

async function main(): Promise<void> {
  console.log('=== CONTENT-1E w-embed recovery migrator ===\n')

  fs.mkdirSync(SNAPSHOT_DIR, { recursive: true })

  const { byDoc, totals } = loadSweepInventory()
  console.log(`Sweep inventory: ${byDoc.size} affected docs (${totals.sourceTotal} embeds total)`)

  // Drift guard #1 — technology + service must remain at zero per Checkpoint 1
  // scope-narrowing. If sweep regrows for those types, halt before patching.
  if (totals.technologyCount > 0 || totals.serviceCount > 0) {
    throw new Error(
      `Drift detected: sweep finds technology=${totals.technologyCount}, service=${totals.serviceCount} embeds (expected 0 each). Re-evaluate scope before re-running this migrator.`,
    )
  }

  // Dedup-aware pre-flight. Multi-collection blogPost mirrors that CONTENT-1C
  // deduplicated against a slug-canonical sibling are skipped with log.
  const docsForClassify = new Map<string, { slug: string | null; type: string }>()
  for (const [docId, entries] of byDoc) {
    docsForClassify.set(docId, { slug: entries[0].slug, type: entries[0].docType })
  }
  const classification = await classifySweepTargets(docsForClassify)
  console.log(
    `Sanity coverage: existing=${classification.existing.size}, dedupedToCanonical=${classification.deduped.length}, orphans=${classification.orphans.length}`,
  )
  if (classification.orphans.length > 0) {
    console.error('Orphan docs (no Sanity record AND no slug-canonical) — halting:')
    for (const o of classification.orphans) console.error(`  ${o.docId} slug=${o.slug ?? '(null)'}`)
    throw new Error(`Halt — ${classification.orphans.length} orphan doc(s) found; content unrecovered.`)
  }
  if (classification.deduped.length > 0) {
    console.log('Deduped (skipped — content recovered via canonical):')
    for (const d of classification.deduped) {
      console.log(`  ${d.docId} → canonical=${d.canonicalIds.join(',')} slug="${d.slug}"`)
    }
  }
  console.log()

  const webflowSource = await buildWebflowSource(SPECS)
  console.log(`Webflow source: ${webflowSource.size} items loaded\n`)

  const errors: string[] = []
  let totalPatched = 0
  let totalEmbedsRecovered = 0
  let totalSkippedDeduped = classification.deduped.length
  const perTypePatched: Record<DocType, number> = {
    blogPost: 0,
    compareBlog: 0,
    customerStory: 0,
  }

  for (const spec of SPECS) {
    // Collect docs for this spec from sweep inventory, filtered to the target
    // Webflow field. Embeds in other fields are skipped (sweep confirmed zero
    // — this guards against future drift).
    const targets: Array<{ docId: string; webflowId: string; slug: string | null; entries: SweepEntry[] }> = []
    for (const [docId, entries] of byDoc) {
      if (entries[0].docType !== spec.docType) continue
      const targetField = entries.filter((e) => e.fieldName === spec.webflowField)
      const otherField = entries.filter((e) => e.fieldName !== spec.webflowField)
      if (otherField.length > 0) {
        errors.push(
          `${docId}: ${otherField.length} embed(s) in non-target field(s) ${[...new Set(otherField.map((e) => e.fieldName))].join(', ')} — scope-narrowing assumption violated; halt.`,
        )
        break
      }
      if (targetField.length === 0) continue
      // Skip deduped — canonical is patched from its own Webflow source.
      if (!classification.existing.has(docId)) continue
      const webflowId = docId.slice(spec.docType.length + 1)
      targets.push({ docId, webflowId, slug: entries[0].slug, entries: targetField })
    }
    if (errors.length > 0) break

    console.log(`[${spec.docType}.${spec.sanityField}] target docs: ${targets.length}`)

    for (const t of targets) {
      try {
        // Per-doc guard 1 — Sanity doc + _type
        const sanityDoc = await sanityWriteClient.getDocument(t.docId)
        if (!sanityDoc) throw new Error('Sanity doc not found')
        if (sanityDoc._type !== spec.docType) {
          throw new Error(`_type mismatch: expected ${spec.docType}, got ${sanityDoc._type}`)
        }

        // Per-doc guard 2 — pre-patch snapshot (OVERRIDE 2)
        const snapFile = snapshotFilename(spec.docType, t.slug, t.webflowId)
        const currentValue = (sanityDoc as Record<string, unknown>)[spec.sanityField]
        fs.writeFileSync(
          snapFile,
          JSON.stringify(
            {
              docId: t.docId,
              docType: spec.docType,
              slug: t.slug,
              sanityField: spec.sanityField,
              webflowId: t.webflowId,
              snapshotTakenAt: new Date().toISOString(),
              expectedEmbedCount: t.entries.length,
              value: currentValue ?? null,
            },
            null,
            2,
          ),
        )

        // Per-doc guard 3 — Webflow source item
        const wfItem = webflowSource.get(t.webflowId)
        if (!wfItem) throw new Error('Webflow item not found in source corpus')
        const html = wfItem.fieldData[spec.webflowField]
        if (typeof html !== 'string' || html.trim() === '') {
          throw new Error(
            `Webflow ${spec.webflowField} is empty — sweep showed ${t.entries.length} embed(s); source drift since sweep ran.`,
          )
        }

        // Per-doc guard 4 — deserialize + structural assertion
        const newPortableText = await toPortableText(html, { webflowId: t.webflowId })
        const typed = newPortableText as Array<{ _type: string }>
        const recovered = typed.filter(
          (b) => b._type === 'videoEmbed' || b._type === 'table',
        ).length
        if (recovered !== t.entries.length) {
          throw new Error(
            `embed count mismatch: deserializer emitted ${recovered} videoEmbed+table blocks, sweep expected ${t.entries.length}`,
          )
        }

        // Per-doc guard 5 — atomic patch
        await sanityWriteClient
          .patch(t.docId)
          .set({ [spec.sanityField]: newPortableText })
          .commit()

        totalPatched++
        perTypePatched[spec.docType]++
        totalEmbedsRecovered += recovered
        console.log(
          `  ✅ ${t.docId} (${t.slug ?? 'no-slug'}): ${recovered} embed(s) recovered — snapshot=${path.basename(snapFile)}`,
        )
      } catch (e) {
        const msg = `${t.docId}: ${(e as Error).message}`
        errors.push(msg)
        console.error(`  ❌ ${msg}`)
        break
      }
    }

    if (errors.length > 0) break
  }

  // parity_score denominator = eligible docs (sweep total minus
  // deduped-to-canonical Webflow mirrors). The 9 deduped docs are
  // CONTENT-1C dedup artefacts whose embed content IS recovered via their
  // slug-canonical siblings — they are NOT unrecovered loss, so they must
  // not weigh down the parity score. Using `byDoc.size` (88) as the
  // denominator instead would yield 79/88 = 89.77, which misrepresents
  // coverage. Eligible count gives the correct 79/79 = 100%.
  const eligibleCount = byDoc.size - totalSkippedDeduped
  await recordMigration({
    collectionSlug: 'w-embed-recovery',
    sourceItemCount: byDoc.size,
    migratedItemCount: totalPatched,
    parityBaselineCount: eligibleCount,
    status: errors.length === 0 ? 'complete' : 'failed',
    errorLog:
      errors.length === 0
        ? [
            'CONTENT-1E w-embed recovery (post-CONTENT-1C patch).',
            `Patched ${totalPatched} docs (${totalEmbedsRecovered} embeds recovered) across {blogPost: ${perTypePatched.blogPost}, compareBlog: ${perTypePatched.compareBlog}, customerStory: ${perTypePatched.customerStory}}.`,
            `Skipped ${totalSkippedDeduped} deduped-against-canonical Webflow mirrors (CONTENT-1C dedup).`,
            'technology + service confirmed zero-embed at sweep + migrator drift-check.',
            'Pre-patch snapshots written to audit-output/content-1e/pre-patch-snapshots/ (rollback escape hatch).',
            `parity_score reflects eligible coverage (${totalPatched}/${eligibleCount} = ${eligibleCount > 0 ? Math.round((totalPatched / eligibleCount) * 100) : 0}%); ${totalSkippedDeduped} deduped-to-canonical Webflow mirrors excluded from denominator per CONTENT-1C dedup.`,
          ]
        : [
            'CONTENT-1E w-embed recovery — halted on first failure (CONTENT-1D-CLEANUP pattern).',
            ...errors,
          ],
  })

  console.log('\n=== SUMMARY ===')
  console.log(`  patched: ${totalPatched} / ${byDoc.size - totalSkippedDeduped} (eligible)`)
  console.log(`  skipped (deduped-to-canonical): ${totalSkippedDeduped}`)
  console.log(`  embeds recovered: ${totalEmbedsRecovered}`)
  console.log(`  per-type: ${JSON.stringify(perTypePatched)}`)
  console.log(`  errors: ${errors.length}`)
  console.log(`  snapshots dir: ${SNAPSHOT_DIR}`)

  if (errors.length > 0) process.exit(1)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
