// Extracts redirect data from audit-output/ into tracked TS files inside
// site/. audit-output/ is gitignored so Vercel cannot read it at build
// time — next.config.ts must only import from tracked files.
//
// Re-run with: npm run redirects:extract
//
// Outputs:
//   site/src/lib/redirects/generated-redirects.ts  — crawl-discovered
//     301/302s from ce-canonical-urls.json (drops null-target rows).
//   site/src/lib/redirects/webflow-redirects.ts    — non-job-role rows
//     from webflow-redirects.csv (the 336 /live-job-role/* rows are
//     collapsed by the catch-all regex in next.config.ts).
//   site/src/lib/redirects/regex-redirects.ts      — 11 Webflow regex
//     rules from ce-regex-redirects.json, translated to Next.js
//     :path* syntax.
//
// Brief deviation noted in DEBUG_CONTEXT.md: brief Step 6d says
// webflow-redirects.ts is "hand-authored from the verified markdown
// source", but that markdown only contains summary stats + 5 examples.
// The 317 actual rows live in webflow-redirects.csv (gitignored), so
// this script extends the same Step 6c extraction pattern to the CSV.

import fs from 'fs'
import { UrlStatus, type CanonicalUrl } from '../../src/lib/audit-types'

interface CanonicalUrlsPayload {
  canonicalUrls: CanonicalUrl[]
}

const REDIRECT_STATUSES: UrlStatus[] = [UrlStatus.REDIRECT_301, UrlStatus.REDIRECT_302]
const LOCKED_RULE_SOURCES = new Set(['/team', '/our-work', '/alternatives'])
const JOB_ROLE_PREFIXES = ['/live-job-role', '/uk/live-job-role', '/ph/live-job-role']

function isJobRolePath(path: string): boolean {
  return JOB_ROLE_PREFIXES.some(
    (prefix) => path === prefix || path.startsWith(`${prefix}/`),
  )
}

// 1. Crawl-discovered redirects from ce-canonical-urls.json
const canonicalPayload: CanonicalUrlsPayload = JSON.parse(
  fs.readFileSync('audit-output/ce-canonical-urls.json', 'utf-8')
)

const crawlRedirects = canonicalPayload.canonicalUrls
  .filter((u) => REDIRECT_STATUSES.includes(u.status))
  // Some crawl rows recorded a 301/302 status without a captured
  // destination. Those cannot become Next.js redirects — the Webflow
  // CSV export covers them.
  .filter((u): u is CanonicalUrl & { redirectTarget: string } =>
    typeof u.redirectTarget === 'string' && u.redirectTarget.length > 0
  )
  .filter((u) => !LOCKED_RULE_SOURCES.has(u.path))
  .map((u) => ({
    source: u.path,
    destination: u.redirectTarget,
    permanent: u.status === UrlStatus.REDIRECT_301,
  }))

const crawlOutput = `// AUTO-GENERATED by scripts/scaffold/extract-redirects.ts
// Do not edit manually. Re-run the script if audit-output/ changes.
import type { Redirect } from 'next/dist/lib/load-custom-routes'

export const crawlRedirects: Redirect[] = ${JSON.stringify(crawlRedirects, null, 2)}
`

fs.mkdirSync('site/src/lib/redirects', { recursive: true })
fs.writeFileSync('site/src/lib/redirects/generated-redirects.ts', crawlOutput)
console.log(`Extracted ${crawlRedirects.length} crawl redirects`)

// 2. Heterogeneous Webflow redirects from webflow-redirects.csv
// Tiny custom CSV parser — the file has just two unquoted columns.
const csvText = fs.readFileSync('audit-output/webflow-redirects.csv', 'utf-8')
const csvRows = csvText
  .split(/\r?\n/)
  .slice(1) // header
  .filter((line) => line.trim().length > 0)
  .map((line) => {
    const idx = line.indexOf(',')
    if (idx === -1) return null
    return { source: line.slice(0, idx).trim(), target: line.slice(idx + 1).trim() }
  })
  .filter((row): row is { source: string; target: string } => row !== null)

// Strip query strings — Next.js source patterns don't match them and
// path-to-regexp rejects '?' as a path modifier. The 3 /media/... rows
// with query strings are also covered by ce-regex-redirects.json (which
// becomes regex-redirects.ts), so dedupe by source after stripping.
const seenSources = new Set<string>()
const webflowRedirects = csvRows
  .filter((row) => !isJobRolePath(row.source))
  .filter((row) => !LOCKED_RULE_SOURCES.has(row.source))
  .map((row) => ({ source: row.source.replace(/\?.*$/, ''), target: row.target }))
  .filter((row) => {
    if (seenSources.has(row.source)) return false
    seenSources.add(row.source)
    return true
  })
  // Webflow exports don't include status codes — every row is a
  // permanent redirect (Webflow's UI only emits 301s for canonicalised
  // moves; CONTENT-1 can downgrade individual rows to 307 if needed).
  .map((row) => ({
    source: row.source,
    destination: row.target,
    permanent: true,
  }))

const webflowOutput = `// AUTO-GENERATED by scripts/scaffold/extract-redirects.ts
// Do not edit manually. Re-run the script if audit-output/ changes.
//
// Source: audit-output/webflow-redirects.csv (gitignored). The 336
// /live-job-role/* rows are collapsed by a catch-all regex in
// next.config.ts; this file holds the remaining 317 heterogeneous
// redirects (page renames, blog rollups, locale moves) preserved
// individually per docs/investigations-2026-04-23/redirects-verification.md.
import type { Redirect } from 'next/dist/lib/load-custom-routes'

export const webflowRedirects: Redirect[] = ${JSON.stringify(webflowRedirects, null, 2)}
`

fs.writeFileSync('site/src/lib/redirects/webflow-redirects.ts', webflowOutput)
console.log(`Extracted ${webflowRedirects.length} Webflow heterogeneous redirects`)

// 3. Webflow regex redirects from ce-regex-redirects.json
// Webflow uses (.*) capture with %1 reference; Next.js uses :path*.
// Strip query strings from sources — Next.js redirect sources don't
// match query strings by default, and the orphan media-file rules in
// CE's regex set are the only ones with queries.
interface WebflowRegexRedirect {
  pattern: string
  target: string
}
interface WebflowRegexPayload {
  count: number
  redirects: WebflowRegexRedirect[]
}

const regexPayload: WebflowRegexPayload = JSON.parse(
  fs.readFileSync('audit-output/ce-regex-redirects.json', 'utf-8'),
)

// Webflow's (.*) capture maps to Next.js path-to-regexp ':slug*'. That
// syntax requires a '/' separator before the parameter. For Webflow rules
// where (.*) is glued directly onto a path segment with no slash (e.g.
// `/tools/price-comparison-calculator(.*)`), emit two Next.js rules:
// one exact match and one `/.../:slug*` match.
function translateWebflowRegex(
  rule: WebflowRegexRedirect,
): Array<{ source: string; destination: string; permanent: boolean }> {
  const cleanedPattern = rule.pattern.replace(/\?.*$/, '')
  const captureCount = (cleanedPattern.match(/\(\.\*\)/g) ?? []).length

  if (captureCount === 0) {
    return [{ source: cleanedPattern, destination: rule.target, permanent: true }]
  }

  const noCapture = cleanedPattern.replace(/\(\.\*\)/g, '')
  const lastChar = noCapture.slice(-1)
  const destination = rule.target.replace(/%1/g, ':slug*')

  if (cleanedPattern.endsWith('/(.*)')) {
    const source = cleanedPattern.replace(/\(\.\*\)/g, ':slug*')
    return [{ source, destination, permanent: true }]
  }

  if (lastChar !== '/') {
    // Webflow's `/foo(.*)` matches `/foo` AND `/foo/...`. Emit two rules
    // because path-to-regexp can't represent that with a single pattern.
    const exactSource = noCapture
    const wildcardSource = `${noCapture}/:slug*`
    const wildcardDest =
      destination === rule.target ? destination : destination
    return [
      { source: exactSource, destination: rule.target.replace(/%1/g, ''), permanent: true },
      { source: wildcardSource, destination: wildcardDest, permanent: true },
    ]
  }

  const source = cleanedPattern.replace(/\(\.\*\)/g, ':slug*')
  return [{ source, destination, permanent: true }]
}

const regexRedirects = regexPayload.redirects.flatMap(translateWebflowRegex)

const regexOutput = `// AUTO-GENERATED by scripts/scaffold/extract-redirects.ts
// Do not edit manually. Re-run the script if audit-output/ changes.
//
// Source: audit-output/ce-regex-redirects.json. Webflow's (.*) + %1
// syntax has been translated to Next.js :slug* path-to-regexp syntax.
import type { Redirect } from 'next/dist/lib/load-custom-routes'

export const regexRedirects: Redirect[] = ${JSON.stringify(regexRedirects, null, 2)}
`

fs.writeFileSync('site/src/lib/redirects/regex-redirects.ts', regexOutput)
console.log(`Extracted ${regexRedirects.length} regex redirects`)
