// Generate the /live-job-role/* redirects from Webflow's actual redirect export.
//
// These used to be a catch-all: `/live-job-role/:path+` -> talent.cloudemployee.io.
// It looked like a tidy collapse of 333 near-identical rows. It was not, and the
// parity gate caught it.
//
// Webflow has an EXPLICIT rule per job slug, and it does not have one for every
// slug that ever existed. 29 job URLs are absent from its list, and Webflow 404s
// them. The catch-all redirected those 29 as well, to a talent-site URL that is
// itself a 404 - so we turned a clean 404 into a cross-domain redirect chain
// ending in a 404, which is worse for a crawler and worse for a visitor.
//
// A pattern that "obviously" generalises a list is a guess about the list. This
// reads the list.
//
//   npm run redirects:job-roles
import { readFileSync, writeFileSync } from 'node:fs'

const CSV = 'data/webflow/webflow-redirects.csv'
const OUT = 'site/src/lib/redirects/job-role-redirects.ts'

type Rule = { source: string; destination: string; permanent: true }

function main(): void {
  const rows = readFileSync(CSV, 'utf8')
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => {
      const i = l.indexOf(',')
      return { source: l.slice(0, i), destination: l.slice(i + 1) }
    })
    .filter((r) => /^\/(uk\/|ph\/)?live-job-role(\/|$)/.test(r.source))

  const rules: Rule[] = rows.map((r) => ({
    source: r.source,
    destination: r.destination.replace(/^"|"$/g, ''),
    permanent: true,
  }))

  // The bare roots are not per-slug and are not always in the export; live 301s
  // them to the talent home page, which is a real 200.
  for (const source of ['/live-job-role', '/uk/live-job-role', '/ph/live-job-role']) {
    if (!rules.some((r) => r.source === source)) {
      rules.push({ source, destination: 'https://talent.cloudemployee.io/', permanent: true })
    }
  }

  const body = `// GENERATED by scripts/scaffold/generate-job-role-redirects.ts - do not hand-edit.
//
// One rule per job slug, taken from Webflow's redirect export, NOT a catch-all.
// Webflow does not redirect every /live-job-role/ URL that ever existed: 29 of them
// are absent from its list and it 404s them, and their talent-site destinations are
// 404s too. A catch-all sent those 29 into a cross-domain redirect chain ending in a
// dead page, which is worse than the clean 404 the live site serves.
//
// Regenerate: npm run redirects:job-roles
import type { Redirect } from 'next/dist/lib/load-custom-routes'

export const jobRoleRedirects: Redirect[] = ${JSON.stringify(rules, null, 2)}
`
  writeFileSync(OUT, body)
  console.log(`${rules.length} job-role rules written to ${OUT}`)
  console.log(`  ${rows.length} from Webflow's export, ${rules.length - rows.length} bare-root rules added`)
}

main()
